In [12]:
# create a Employee class
class Employee(object):
    # create a data member to count the number of Employees
    employeeCount = 0

    # create a constructor to initialize variables
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employeeCount += 1

    # create a function to average salary
    def average_salary(self):
        return self.salary / Employee.employeeCount

# create a Fulltime Employee class tkok inherit the properties of Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self, name, family, salary, department)

Employee_One = Employee("Prathap", "Boddu", 1000, "IT")
Employee_Two = FulltimeEmployee("Siddu", "Katta", 2000, "Marketing")

print("Average Salary:", Employee_One.average_salary())

Average Salary: 500.0


In [1]:
import numpy as np

# numpy array with random values in 4 by 5 size
randNumArray = np.random.uniform(low=1, high=20, size=(4,5))

# finding the indices with maximum values
maxIndices = np.argmax(randNumArray, axis=1)

# finding the row indices
rowIndices = np.arange(randNumArray.shape[0])

# finding the exact positions of maximium valuesin the array
positionIndices = np.array([rowIndices, maxIndices])

# to convert the array into an array of flat indices
linearIndices = np.ravel_multi_index(positionIndices, randNumArray.shape)

# reshaping the linear array into multi dimensionanl array
randNumArray.reshape((-1))[linearIndices] = 0

print(randNumArray)

[[ 2.8598382  17.71237138 14.3538226   0.          5.95496805]
 [ 0.          2.23773923 13.64836067  8.98679133  1.26413173]
 [ 6.48855674  1.32567986 10.05520168  0.          6.38842617]
 [ 2.98658322  9.45674619  0.         17.59829801 11.60048845]]
